"""Pre-flight: build Judge's debate-scoring criteria from web research.

Lec05 L1519-1528: the lecturer wanted scoring criteria sourced from real-world
parliamentary debate authority, not invented. This script web-searches for
"parliamentary debate scoring criteria", "Lincoln-Douglas format",
"Robert's Rules of Order", and "World Schools Debate Championship judging axes"
and synthesizes the results into the Judge's reference doc.

Idempotent: if the output file exists, prints a cache-hit message and exits 0
without hitting the network. Re-run after deleting the file to refresh.

On DuckDuckGo rate-limit (SearchRateLimited), the per-query block is skipped
with a visible "(DDG rate-limited; skipping)" note rather than aborting — the
output is still written so downstream Judge-skill loading does not break.
"""
from __future__ import annotations

import sys
from pathlib import Path

from agent_debate.tools.duckduckgo_provider import (
    DuckDuckGoProvider,
    SearchRateLimited,
)

OUTPUT_PATH = Path(".claude/skills/judge_skill/references/debate_criteria.md")

QUERIES: list[str] = [
    "parliamentary debate scoring criteria",
    "Lincoln-Douglas debate format judging criteria",
    "Robert's Rules of Order debate procedure",
    "World Schools Debate Championship judging axes",
]


def _build_header() -> list[str]:
    return [
        "# Debate Criteria — sourced via web research",
        "",
        "> Auto-generated by `scripts/build_judge_criteria.py`. Synthesizes "
        "real-world debate-scoring practice from authoritative sources for the "
        "Judge agent's reference. Re-run after deleting this file to refresh.",
        "",
    ]


def _section_for_query(provider: DuckDuckGoProvider, query: str) -> list[str]:
    section: list[str] = [f"## Query: {query}", ""]
    try:
        hits = provider.search(query, k=3)
    except SearchRateLimited as exc:
        section.append(f"_(DDG rate-limited; skipping. Reason: {exc})_")
        section.append("")
        return section
    if not hits:
        section.append("_(no results returned)_")
        section.append("")
        return section
    for hit in hits:
        snippet = (hit.snippet or "").strip().replace("\n", " ")
        snippet_short = snippet[:160] if snippet else "(no snippet)"
        section.append(f"- [{snippet_short}]({hit.url})")
    section.append("")
    return section


def main() -> int:
    if OUTPUT_PATH.exists():
        print(f"Cache hit: {OUTPUT_PATH} — skipping")
        return 0

    provider = DuckDuckGoProvider()
    body: list[str] = _build_header()

    for query in QUERIES:
        body.extend(_section_for_query(provider, query))

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(body), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({len(body)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
